

services:
  db:
    image: mysql:8
    container_name: szkodnikrp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: szkodnikrp
    volumes:
      - szkodnikrp-db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  samp:
    build: .
    container_name: szkodnikrp-samp
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "7777:7777/udp"
    volumes:
      - .:/app

volumes:
  szkodnikrp-db_data:
