

services:
  db:
    image: mysql:8
    container_name: szkodnikrp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: szkodnikrp
    volumes:
      - szkodnikrp-db_data:/var/lib/mysql
    networks:
      - szkodnikrp-network
    ports:
      - "3307:3306"  # port hosta zmieniony na 3307, żeby nie kolidował

  samp:
    build: .
    container_name: szkodnikrp-samp
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - szkodnikrp-network
    ports:
      - "7777:7777/udp"
    volumes:
      - .:/app

volumes:
  szkodnikrp-db_data:

networks:
  szkodnikrp-network:
    driver: bridge
