version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: szkodnikrp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: szkodnikrp
      MYSQL_USER: www
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  samp:
    container_name: szkodnikrp-samp
    build: ./samp
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./gamemodes:/usr/src/app/gamemodes
      - ./pawn.json:/usr/src/app/pawn.json
    ports:
      - "7777:7777/udp"
    command: >
      bash -c "sampctl package ensure && sampctl server run"

volumes:
  db_data:
